FROM debian:buster as dnsmasq

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update --quiet > /dev/null && \
    apt-get install --quiet --quiet --no-install-recommends \
        tftpd-hpa
ENTRYPOINT in.tftpd
