---
version: "3.4"
# Base service; for extension only, not for direct use
x-service-base: &service_base
  image: "${DOCKER_REPOSITORY-ivan-c/}${DOCKER_IMAGE_NAME:-cobbler}:${DOCKER_IMAGE_TAG:-latest}"
  build: .
services:
  cobblerd:
    <<: *service_base
    entrypoint: /bin/entrypoint.sh
    command:
      - cobblerd
      - --no-daemonize
      - --log-level=INFO
    ports:
      # cobblerd port
      - 25151
      # httpd (apache) port
      - 80
    volumes:
      - ./docker-entrypoint.sh:/bin/entrypoint.sh:ro
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro
      - config-data:/etc/cobbler/
      - ./media:/media
  cobbler-web:
    <<: *service_base
    # cobblerd is hard-coded to only listen on 127.0.0.1
    # https://github.com/cobbler/cobbler/blob/v2.8.4/cobbler/cobblerd.py#L108
    network_mode: service:cobblerd
    entrypoint: httpd
    command:
      - -DFOREGROUND
      - -cTransferLog /dev/stdout
      - -cServerName cobbler-web
    depends_on: [cobblerd]
volumes:
  config-data: {}
