FROM debian:buster as dnsmasq

ENV DEBIAN_FRONTEND=noninteractive

# Install tools for reading build dependencies; see `Build-Depends`
# Squelch superfluous output; apt-get has poor verbosity control
RUN \
    apt-get update --quiet > /dev/null && \
    apt-get install --quiet --quiet --no-install-recommends \
        tftpd-hpa
ENTRYPOINT in.tftpd
