FROM debian:buster

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update --quiet > /dev/null && \
    apt-get install --quiet --quiet --no-install-recommends \
        atftpd
ENTRYPOINT in.tftpd
