---
version: "3.4"
# Base service; for extension only, not for direct use
x-service-base: &service_base
  image: "${DOCKER_REPOSITORY-ivan-c/}${DOCKER_IMAGE_NAME:-cobbler}:${DOCKER_IMAGE_TAG:-latest}"
  build:
    context: .
    target: "${DOCKER_STAGE:-cobbler_base}"
services:
  cobblerd:
    <<: *service_base
    entrypoint: /bin/entrypoint.sh
    command:
      - cobblerd
      - --no-daemonize
      - --log-level=INFO
    ports:
      # cobblerd port
      - 25151
      # httpd (apache) port
      - 80
    volumes:
      - ./docker-entrypoint.sh:/bin/entrypoint.sh:ro
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro
      - ./media:/media
      - config-data:/etc/
      - tftp-data:/var/lib/tftpboot
    environment:
      next_server: ${next_server}
      server: ${server}
  cobbler-web:
    <<: *service_base
    # cobblerd is hard-coded to only listen on 127.0.0.1
    # https://github.com/cobbler/cobbler/blob/v2.8.4/cobbler/cobblerd.py#L108
    network_mode: service:cobblerd
    entrypoint: httpd
    command:
      - -DFOREGROUND
      - -cTransferLog /dev/stdout
      - -cServerName cobbler-web
    depends_on: [cobblerd]
  cobbler-dnsmasq:
    <<: *service_base
    network_mode: host
    entrypoint: dnsmasq
    command:
      - --keep-in-foreground
      - --user=root
    volumes:
      - config-data:/etc/:ro
    ports:
      # DHCP
      - "67:67/udp"
  cobbler-tftp:
    <<: *service_base
    network_mode: host
    entrypoint: in.tftpd
    command:
      - --foreground
      - --secure
      - /var/lib/tftpboot
    volumes:
      - tftp-data:/var/lib/tftpboot:ro
    ports:
      # TFTP
      - "69:69"
volumes:
  config-data: {}
  tftp-data: {}
