---
version: "3.4"
# Base service; for extension only, not for direct use
x-service-base: &service_base
  image: "${DOCKER_REPOSITORY-ivan-c/}${DOCKER_IMAGE_NAME:-cobbler}:${DOCKER_IMAGE_TAG:-latest}"
  build:
    context: .
    target: "${DOCKER_STAGE:-cobbler_base}"
services:
  cobblerd:
    <<: *service_base
    entrypoint: /bin/entrypoint.sh
    command:
      - cobblerd
      - --no-daemonize
      - --log-level=INFO
    ports:
      # cobblerd port
      - 25151
      # httpd (apache) port
      - 80:80
    volumes:
      - ./docker-entrypoint.sh:/bin/entrypoint.sh:ro
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro

      - ./docker-post-deploy.sh:/bin/docker-post-deploy.sh:ro
      - ./post-deploy.d:/post-deploy.d:ro

      - ./media:/media
      - httpd-data:/etc/httpd/
      - tftpd-data:/var/lib/tftpboot
    environment:
      debian_release: ${debian_release:-buster}
      server: ${server}
      # must be IP address (not domain)
      next_server: ${next_server}
    env_file:
      - cobbler.env
  cobbler-web:
    <<: *service_base
    # cobblerd is hard-coded to only listen on 127.0.0.1
    # https://github.com/cobbler/cobbler/blob/v2.8.4/cobbler/cobblerd.py#L108
    network_mode: service:cobblerd
    entrypoint: httpd
    command:
      - -DFOREGROUND
      - -cTransferLog /dev/stdout
      - -cServerName cobbler-web
    depends_on: [cobblerd]
  dnsmasq:
    image: "${DOCKER_REPOSITORY-ivan-c/}${DOCKER_IMAGE_NAME:-dnsmasq}:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile.dnsmasq
    network_mode: host
    entrypoint: dnsmasq
    command:
      - --log-facility=-
      - --log-queries
      #- --log-dhcp
      - --keep-in-foreground
      - --user=root
      - --dhcp-range=192.168.1.0,proxy
      - --expand-hosts
      - --pxe-service=x86PC,Boot PXELinux (=Cobbler controlled),pxelinux,$next_server
      - --pxe-prompt=Booting default...,5
    ports:
      # DHCP
      - "67:67/udp"
    volumes:
      - httpd-data:/etc/httpd/:ro
  tftpd:
    image: "${DOCKER_REPOSITORY-ivan-c/}${DOCKER_IMAGE_NAME:-tftpd}:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile.tftpd
    entrypoint: in.tftpd
    command:
      - --daemon
      - --no-fork
      - --user=root
      - --bind-address=0.0.0.0
      - --port=69
      - --verbose
      - --logfile=-
      - /var/lib/tftpboot
    volumes:
      - tftpd-data:/var/lib/tftpboot:ro
    ports:
      # TFTP
      - "69:69/udp"
volumes:
  httpd-data: {}
  tftpd-data: {}
